# Generated by Django 5.1.2 on 2024-10-20 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_formularios'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preguntas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoInput', models.IntegerField()),
                ('contenido', models.CharField(max_length=50)),
                ('idFormulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.formularios')),
            ],
        ),
    ]
