# Generated by Django 5.1.2 on 2024-10-20 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_preguntas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preguntas',
            name='tipoInput',
            field=models.CharField(max_length=50),
        ),
    ]
